package cn.lsk.safetybelt.po;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.state0
     *
     * @mbggenerated
     */
    private Integer state0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.state1
     *
     * @mbggenerated
     */
    private Integer state1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.state2
     *
     * @mbggenerated
     */
    private Integer state2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.state3
     *
     * @mbggenerated
     */
    private Integer state3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.height
     *
     * @mbggenerated
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.power
     *
     * @mbggenerated
     */
    private Double power;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.user_id
     *
     * @return the value of device.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.user_id
     *
     * @param userId the value for device.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.state0
     *
     * @return the value of device.state0
     *
     * @mbggenerated
     */
    public Integer getState0() {
        return state0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.state0
     *
     * @param state0 the value for device.state0
     *
     * @mbggenerated
     */
    public void setState0(Integer state0) {
        this.state0 = state0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.state1
     *
     * @return the value of device.state1
     *
     * @mbggenerated
     */
    public Integer getState1() {
        return state1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.state1
     *
     * @param state1 the value for device.state1
     *
     * @mbggenerated
     */
    public void setState1(Integer state1) {
        this.state1 = state1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.state2
     *
     * @return the value of device.state2
     *
     * @mbggenerated
     */
    public Integer getState2() {
        return state2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.state2
     *
     * @param state2 the value for device.state2
     *
     * @mbggenerated
     */
    public void setState2(Integer state2) {
        this.state2 = state2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.state3
     *
     * @return the value of device.state3
     *
     * @mbggenerated
     */
    public Integer getState3() {
        return state3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.state3
     *
     * @param state3 the value for device.state3
     *
     * @mbggenerated
     */
    public void setState3(Integer state3) {
        this.state3 = state3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.height
     *
     * @return the value of device.height
     *
     * @mbggenerated
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.height
     *
     * @param height the value for device.height
     *
     * @mbggenerated
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.power
     *
     * @return the value of device.power
     *
     * @mbggenerated
     */
    public Double getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.power
     *
     * @param power the value for device.power
     *
     * @mbggenerated
     */
    public void setPower(Double power) {
        this.power = power;
    }
}